df<-read.table("./household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors = FALSE)
df[,1]<-as.Date(df[,1],format="%d/%m/%Y")
df2<-subset(df,Date=="2007-02-01"|Date=="2007-02-02")
df2[,3:9]<-lapply(df2[,3:9],function (x) as.numeric(x))
png(file="./plot1.png",width=480,height = 480)
hist(df2$Global_active_power,col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.off()
